# -*- coding: utf-8 -*-
"""fancyindexing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BhAE0t4gqHFzvKJ8QwYsIdgEDcch4u58
"""

import numpy as np
a=np.random.randint(1, 11, 10)
a

print(a[1])
print(a[2])

indices=[1,4,7]
a1=[]
for i in indices:
    a1.append(a[i])

np.array(a1)

#fancy indexing--> fancy indexing is technique in programming especailly in numpy,
#that allows you to select multiple elements from an array at once using list or array.
a[[1,4,7]]

a=np.arange(1, 11)
#here we are creating the view of the original array

view_a=a.view()
#here we are changing the first element of the duplicated array
view_a[0]=100

print(f'original array: {a}')
print(f'view array: {view_a}')
#view is a method which copies the refrence of the original object or
#array whenever we want to change anything into the duplicate array then
#it would effect on the original array

arr= np.arange(1,11)
copy_arr=arr.copy()
copy_arr

copy_arr[1]=20
copy_arr
arr

#this copy method is used to copy the object and create actual same object at different location
#into this the original object is affected when we change the copied duplicated array

#where function or method is used to find the indices on the bassis of same condition.
np.where(arr > 5, 'high','low')

#stacking..
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])

#vertical staking is used to stack the array into the stack format vertically.
np.vstack((arr1,arr2,arr3))

#take an array ranging b/w 10 to 35
#18<child
#18>adult
arr=np.arange(10,35)
np.where(arr >18,'adult','child')

#horizontal stacking..
np.hstack([arr1,arr2])

matrix=np.arange(1,13).reshape(3,4)
arr=np.array([1,2,3]).reshape(3,1)
np.hstack([matrix,arr])