# -*- coding: utf-8 -*-
"""pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jUZ5Wxy-lMABxPVzweCVWs5aZH2isw4i
"""

import pandas as pd
df=pd.read_csv('/content/sample_data/california_housing_test.csv')
df

#df.sample is used to retrive the random rows from the dataframe
#df.sample by default give any one random row from the dataframe
#but if we n rows from the dataframe df.sample(n)
df.sample(5)

df.tail()
#df.tail is used to retrive the last 5 rows the df.

df=pd.read_csv('/content/covid_toy - covid_toy.csv')
df
#the data is divided mainly into the two parts:
#1.numerical-->age,marks,salary
#2.categorical-->gender,customer name
df.info()
df.describe()

df.describe()
#df.describe is used to show five point summary of the data or it
#shows the statistical property of the data on the numerical columns
#five point summary:
#minimum-->min-->0th percentile
#25th percentile
#50th percentile
#75th percentile
#max-->100 percentile
#count-->shows the total numbers of the entries
#it shows the mean and standard deviation of the numerical column.

df.isna().sum()
#df.isna()-->return true or false by checking whether the row entry
#is null or not--> if the row entry is null then it return true
#if row entru is not null then it return false

#df.isna().sum()--> it return the total numbers of null values from the
#data frame along with their column names.

df['fever'].isna().sum()

df.fillna(0,inplace=True)
#df.fillna is used to fill the null values with some value
#inplace=true is used to change into the original dataframe.

df['city'].value_counts()
#to find the total numbers of values count of the each category of the categorical columns
#we use value.counts() method.