# -*- coding: utf-8 -*-
"""pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZ2uI5hAXWAutWbu8rdeqJchnZG_crID
"""

#series
#dataframe

#make a series of 1 to 10 numbers
#add a condition to filter the even entries of the series.
import pandas as pd
my_series = pd.Series([1,2,3,4,5,6,7,8,9,10])
my_series

my_series[my_series%2==0]

#make a series of the 10 to 100 filter odd number and add 5 to each of the elements.
my_series1=pd.Series(range(10,101))
my_series1

my_series1[my_series1%2!=0]

my_series1+5

#dataframes-->2d label data structure(like excel table)
#creating dataframe from a dictionary of lists.
data={
    'name':['alice','bob','charlie','david'],
    'Age':[25,30,35,40],
    'City':['New York','San Francisco','Los Angeles','Chicago'],
    'gender':['male','female','male','male']
}
df=pd.DataFrame(data)
df

df[df['Age']>24]

df['Age'].mean()

df['gender'].mode()

df['Age'].median()

df['Age'].max()

df['Age'].min()

#accessing rows in dataframe.
#loc-->label based indexing
#Iloc-->integer based indexing
df.loc['a']

#accessing multiple rows using list
df.loc[['a','b']]

df.loc[['a','b'],['name','City']]

#find all the rows and columns of the elements of the dataframe using loc.
df.loc[:,:]

#iloc-->interger based indexing..
df.iloc[0]

df.iloc[0:4,0:2]

df.iloc[2:4,2:4]

#df-->occupation
#add a new column occupation
import numpy as np
df['occupation']=pd.Series(['student','working professional',np.nan,'student'])
df

#add 3 columns of maths,science,english marks
df['maths']=pd.Series([40,50,60,70])
df['science']=pd.Series([50,60,70,80])
df['english']=pd.Series([60,50,80,65])
df