# -*- coding: utf-8 -*-
"""pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19iuyEwzDOwiFqdHjwsO8la-hBfBmXkYO
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/Amazon Sale Report.csv.zip')

df

df.tail()

df.head()

df.sample()

df.shape

df.info()

df.isna().sum()

categorical_col=df.select_dtypes(include=object).columns
numerical_col=df.select_dtypes(exclude=object).columns

categorical_col

numerical_col

#Check how many missing values are present in each column.
df.isna().sum()



#2. Find the total number of missing values in the dataset.
df.isnull().sum().sum()

#3. Fill missing values in Amount with the mean value.
df['amount'].fillna(df['amount'].mean(),inplace=True)

#4. Fill missing values in Qty with 0
df['qty'].fillna(0,inplace=True)

#5. Drop rows where Date is missing.
df.dropna