# -*- coding: utf-8 -*-
"""pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sZRU_vDoPhKTV86MjsoKlkAeoVJcAwlL
"""

import pandas as pd
df=pd.read_csv('/covid_toy - covid_toy.csv')
df

#difference b/w loc and ilock
#loc-->label based indexing  syntax--> df.loc(['a','b'],['name','subject'])
#iloc-->by default integer indexing syntax-->df.iloc[0:3,0:2]
#while slicing the rows and columns you don't

df.loc[:,['gender','city']]

df.iloc[0:3,0:2]

df.tail()

df.sample()

import seaborn as sns
df=sns.load_dataset('tips')

df['time'].unique()

df['time'].value_counts()

df['day'].value_counts()

df

df.drop(['tip'],axis=1, inplace=True)
#if we wnt to drop any column axis=1, list of the columns['clo1','col2']

# for droping the rows we can pass the rows index into the drop function
#axis is already 0,
df.drop(0,inplace=True)

df.drop(index=[1,2,3],inplace=True)

df.columns

df.drop(columns=['sex','smoker'],inplace=True)
#for droping the multiple columns we can use the columns=[list of col]

#filtterd the data frame for the numerical columns
df.select_dtypes(exclude='category')
#for categorical columns
df.select_dtypes(include='category')

df['size'].mean()

df['size'].median()

df['size'].mode()

df1={
    'a':[10,20,30],
    'b':['a','b','c']
}
df2={
    'a':[10,20,30],
    'b':['a','b','c']
}
df1=pd.DataFrame(df1)
df2=pd.DataFrame(df2)

pd.concat([df1,df2],axis=0)
#pd.concat is used to concat the two or more dfs using axis
#if ypu want to concat the two dfs by vertically the you have to change axis to 0
#if the columns are not same into the dfs, then the new columns will be created.

#if you want to add the two dfs then it the axis=1
#then the new df would be created with some more columns