# -*- coding: utf-8 -*-
"""test_pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A0tVR1pctnIDYnwFav0zspgecYCfcjx1
"""

import pandas as pd

df=pd.read_csv('/content/titanic - titanic.csv')

df

##SECTION A — BASIC OPERATIONS
#1. Load the Titanic dataset into a pandas DataFrame.
df=pd.read_csv('/content/titanic - titanic.csv')
df

#2. Display the first 5 rows of the DataFrame.
df.head()

#3. Display the last 5 rows of the DataFrame.
df.tail()

#4. Print the number of rows and columns in the dataset.
df.shape

#5. Display all column names and their data types.
df.columns
df.dtypes

#6. Show a statistical summary of all numerical columns.
df.describe()

#7. Show the count of non-null values per column.
df.count()

#SECTION B — MISSING VALUES & CLEANING
#1. Identify which columns contain missing values.
df.isnull().any()

#2. Count missing values in each column.
df.isnull().sum()

#3. Drop the Cabin column from the DataFrame.
df.drop(columns=['Cabin'],inplace=True)
df

#4. Fill missing values in Age with the mean age.
df['Age'].fillna(df['Age'].mean(),inplace=True)
df

#5. Fill missing values in Embarked with the most frequent port.
df['Embarked'].fillna(df['Embarked'].mode()[0],inplace=True)
df

#6. Check that there are no missing values left in Age and Embarked.
df[['Age','Embarked']].isnull().sum()

#7. Remove duplicate rows if any.
df.drop_duplicates()

SECTION C — DATA MANIPULATION
1. Convert the Sex column into a numeric format (e.g., male → 0, female → 1).
2. Convert the Embarked column to a categorical datatype.
3. Create a new column FamilySize = SibSp + Parch + 1.
4. Create a new column IsAlone where 1 indicates the passenger is alone
(FamilySize == 1), else 0.
5. Rename the column Pclass to PassengerClass.
6. Convert Fare to integer values.

#SECTION C — DATA MANIPULATION
#1. Convert the Sex column into a numeric format (e.g., male → 0, female → 1).
df['Sex']=df['Sex'].map({'male':0,'female':1})
df

#2. Convert the Embarked column to a categorical datatype.
df['Embarked']=df['Embarked'].astype('category')
df.dtypes

#3. Create a new column FamilySize = SibSp + Parch + 1.
df['FamilySize']=df['SibSp']+df['Parch']+1
df

#4. Create a new column IsAlone where 1 indicates the passenger is alone.
df['IsAlone']=(df['FamilySize']==1).astype(int)
df

#5. Rename the column Pclass to PassengerClass.
df.rename(columns={'Pclass':'PassengerClass'},inplace=True)
df

#6. Convert Fare to integer values.
df['Fare']=df['Fare'].astype(int)
df.dtypes

#SECTION D — FILTERING & SELECTION
#1. Filter and display all passengers who survived (Survived == 1).
df[df['Survived']==1]

#2. Get passengers who are in 1st class (PassengerClass == 1).
df[df['PassengerClass']==1]
df

#3. Filter passengers whose age is greater than 50.
df[df['Age']>50]

#4. Filter female passengers who survived.
df[(df['Sex']==1)&(df['Survived']==1)]
df

#5. Select passengers who paid a fare above the average fare.
df[df['Fare']>df['Fare'].mean()]
df

#6. Select only columns: Name, Sex, Age, Survived.
df[['Name','Sex','Age','Survived']]
df

#7. Using loc, select rows from index 100 to index 150 (inclusive).
df.loc[100:150]

#8. Using iloc, select the first 10 rows and first 6 columns.
df.iloc[0:10,0:6]

#SECTION E — SORTING & AGGREGATION
1. Sort passengers by Fare in descending order.
2. Sort passengers first by PassengerClass, then by Fare in descending
order.
3. Find the average age of passengers.
4. Compute the average fare paid by each passenger class.
5. Count the number of passengers in each embarkation port.
6. Count how many male and female passengers there are.

##SECTION E — SORTING & AGGREGATION
#1. Sort passengers by Fare in descending order.
df.sort_values(by='Fare',ascending=False)

#2. Sort passengers first by PassengerClass, then by Fare in descending order.
df.sort_values(by=['PassengerClass','Fare'],ascending=[True,False])

#3. Find the average age of passengers.
df['Age'].mean()

#4. Compute the average fare paid by each passenger class.
df.groupby('PassengerClass')['Fare'].mean()

#5. Count the number of passengers in each embarkation port.
df['Embarked'].value_counts()

#6. Count how many male and female passengers there are.
df['Sex'].replace({0:'Male',1:'Female'}).value_counts()

#SECTION F — GROUPBY & APPLY
#1. Group the dataset by PassengerClass and compute:
#○ mean age
#○ mean fare
#○ survival rate (mean of Survived)
df.groupby('PassengerClass').agg({'Age':'mean','Fare':'mean','Survived':'mean'})

#2. Find the survival rate by gender.
df.groupby('Sex')['Survived'].mean()

#3. Use apply() to create a new column AgeGroup:
#○ "Child" if Age < 12
#○ "Adult" if 12 ≤ Age < 60
#○ "Senior" if Age ≥ 60
df['AgeGroup']=df['Age'].apply(lambda x: 'Child' if x<12 else ('Adult' if x<60 else 'Senior'))
df

#4. Reset the index of the grouped result from question 35.